# Generated by Django 6.0.2 on 2026-04-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('total_copies', models.IntegerField(default=1)),
                ('available_copies', models.IntegerField(default=1)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, default='General', max_length=100)),
                ('read_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('gutenberg', 'Gutenberg'), ('openlibrary', 'Open Library'), ('google', 'Google Books'), ('archive', 'Internet Archive')], default='openlibrary', max_length=50)),
                ('book_title', models.CharField(blank=True, default='', max_length=500)),
                ('book_author', models.CharField(blank=True, default='', max_length=300)),
                ('book_cover', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('gutenberg', 'Gutenberg'), ('openlibrary', 'Open Library'), ('google', 'Google Books'), ('archive', 'Internet Archive')], default='openlibrary', max_length=50)),
                ('book_title', models.CharField(blank=True, default='', max_length=500)),
                ('book_author', models.CharField(blank=True, default='', max_length=300)),
                ('book_cover', models.URLField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('progress_percent', models.FloatField(default=0.0)),
                ('is_finished', models.BooleanField(default=False)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_read_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('minutes_read', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
