# Generated by Django 6.0.2 on 2026-04-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GutenbergIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gut_id', models.IntegerField(unique=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('authors', models.JSONField(default=list)),
                ('cover_url', models.URLField(blank=True, default='')),
                ('read_url', models.URLField(blank=True, default='')),
                ('subjects', models.JSONField(default=list)),
                ('bookshelves', models.JSONField(default=list)),
                ('download_count', models.IntegerField(default=0)),
                ('indexed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-download_count'],
                'indexes': [models.Index(fields=['title'], name='books_guten_title_ff6025_idx')],
            },
        ),
    ]
