# Generated by Django 6.0.2 on 2026-03-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_cover_url_book_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='gutenberg_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='read_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
