# Generated by Django 6.0.2 on 2026-04-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_gutenbergindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='readingactivity',
            name='finished_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='readingactivity',
            name='last_read_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='readingsession',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
