# Generated by Django 6.0.2 on 2026-04-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_bookmarks_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(db_index=True, max_length=1000, unique=True)),
                ('content_type', models.CharField(max_length=50)),
                ('image_data', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
