# Generated by Django 6.0.2 on 2026-03-31 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_fix_readinghistory_and_bookmarks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readinghistory',
            options={},
        ),
        migrations.RemoveField(
            model_name='book',
            name='gutenberg_id',
        ),
        migrations.RemoveField(
            model_name='readinghistory',
            name='book',
        ),
        migrations.AddField(
            model_name='readinghistory',
            name='book_id',
            field=models.CharField(default='gutenberg:0', max_length=255),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='readinghistory',
            name='finished_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='readinghistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
