# Generated by Django 6.0.2 on 2026-02-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fine_paid',
            field=models.BooleanField(default=True),
        ),
    ]
